# Generated by Django 3.1.4 on 2020-12-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название отдела')),
            ],
        ),
    ]
