# Generated by Django 3.1.4 on 2020-12-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('subdep_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название подотдела')),
                ('dep_name', models.ForeignKey(db_column='dep_name', on_delete=django.db.models.deletion.CASCADE, to='uchet.department')),
            ],
        ),
    ]
