# Generated by Django 3.1.4 on 2020-12-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0002_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_position', models.CharField(default='Без должности', max_length=50, verbose_name='Должность сотрудника')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('emp_surname', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('emp_birthdate', models.DateTimeField(verbose_name='Дата рождения сотрудника')),
                ('employment_date', models.DateTimeField(verbose_name='Дата устройства на работу')),
                ('dep_name', models.ForeignKey(db_column='dep_name', on_delete=django.db.models.deletion.CASCADE, to='uchet.department')),
                ('subdep_name', models.ForeignKey(db_column='subdep_name', on_delete=django.db.models.deletion.CASCADE, to='uchet.subdepartment')),
            ],
        ),
    ]
