# Generated by Django 3.1.4 on 2020-12-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='subdep_name',
            field=models.ForeignKey(db_column='subdep_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='uchet.subdepartment'),
        ),
    ]
