# Generated by Django 3.1.4 on 2020-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0005_auto_20201211_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='emp_salary',
            field=models.IntegerField(default=0, verbose_name='Зарплата сотрудника'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='emp_birthdate',
            field=models.DateField(verbose_name='Дата рождения сотрудника'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='employment_date',
            field=models.DateField(verbose_name='Дата устройства на работу'),
        ),
    ]
